name: CI Pipeline

on:
  push:
    branches:
      - seguimiento-1
  pull_request:
    branches:
      - seguimiento-1

jobs:
  test:
    runs-on: ubuntu-latest

    env:
        FIREBASE_SERVICE_ACCOUNT_KEY: ${{ secrets.SERVICE_ACCOUNT_KEY_TEST }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Install dependencies
        run: npm install

      - name: Run tests
        run: npm test
      
      - name: Check test coverage
        run: |
          COVERAGE=$(npm run test:coverage --silent | grep 'All files' | awk '{print substr($5, 1, length($5)-1)}')
          if (( $(echo "$COVERAGE < 60" | bc -l) )); then
            echo "Test coverage below 60%!"
            exit 1
          fi
      
